version: '3.7'

services:
  postgres:
    restart: unless-stopped
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql

  api:
    extends:
      file: ./compose.base.yml
      service: nx-app-base
    command: pnpm nx run api:serve
    environment:
      HOST: 0.0.0.0
    ports:
      - 3000:3000

  front:
    extends:
      file: ./compose.base.yml
      service: nx-app-base
    command: pnpm nx run front:serve
    environment:
      DOCKER: true
    ports:
      - 4200:4200

volumes:
  postgres:
