commit_message: 'i18n: update translations (%language%)'
append_commit_message: false
files:
  - source: /apps/front/public/locales/en.json
    translation: /apps/front/public/locales/%two_letters_code%.json
