version: '3.7'

services:
  postgres:
    restart: unless-stopped
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql

  api:
    extends:
      file: ./compose.base.yml
      service: nx-app-base
    command: pnpm nx run api:serve
    environment:
      HOST: 0.0.0.0
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    env_file:
      - ../apps/api/.env
    volumes:
      - cdn:$CDN_PATH
    ports:
      - 3000:3000

  front:
    extends:
      file: ./compose.base.yml
      service: nx-app-base
    command: pnpm nx run front:serve
    environment:
      DOCKER: true
    ports:
      - 4200:4200
      - 5555:5555

  cdn:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ../docker/cdn/nginx.conf:/etc/nginx/nginx.conf
      - cdn:/var/www/cdn

  watcher:
    extends:
      file: ./compose.base.yml
      service: nx-app-base
    command: pnpm nx watch --projects=api,api-server,api-client,content,database,types --includeDependentProjects -- nx run $$NX_PROJECT_NAME:build:development

volumes:
  postgres:
  cdn:
