version: '3.7'

services:
  postgres:
    restart: unless-stopped
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - university

  api:
    image: university-api
    restart: always
    env_file:
      - ./.env
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    expose:
      - 3000
    volumes:
      - ./data/cdn:$CDN_PATH
    labels:
      - traefik.enable=true
      - traefik.http.routers.university-api.rule=Host(`api.sovereignuniversity.org`)
      - traefik.http.routers.university-api.entrypoints=https,http
      - traefik.http.routers.university-api.tls=true
      - traefik.http.routers.university-api.tls.certresolver=security
      - traefik.http.services.university-api.loadbalancer.server.port=3000
      - traefik.http.routers.university-api.service=university-api
    networks:
      - university

  cdn:
    image: nginx:latest
    volumes:
      - ./config/cdn/nginx.conf:/etc/nginx/nginx.conf
      - ./data/cdn:/var/www/cdn
    labels:
      - traefik.enable=true
      - traefik.http.routers.university-cdn.rule=Host(`cdn.sovereignuniversity.org`)
      - traefik.http.routers.university-cdn.entrypoints=https,http
      - traefik.http.routers.university-cdn.tls=true
      - traefik.http.routers.university-cdn.tls.certresolver=security
    networks:
      - university

  front:
    image: university-front
    volumes:
      - ./config/front/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - traefik.enable=true
      - traefik.http.routers.university-front.rule=Host(`sovereignuniversity.org`)
      - traefik.http.routers.university-front.entrypoints=https,http
      - traefik.http.routers.university-front.tls=true
      - traefik.http.routers.university-front.tls.certresolver=security
      - traefik.http.middlewares.university-front.compress=true
    networks:
      - university

networks:
  university:
    external: true
