name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm build

      - name: Lint Code
        run: pnpm lint

      # TODO: Add back when we have tests
      # - name: Run Tests
      #   run: pnpm

  deploy:
    needs: build_and_test
    if: (github.event_name == 'push') && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      - name: Set Docker image metadata for api
        uses: docker/metadata-action@v5
        id: meta-api
        with:
          images: ghcr.io/decouvrebitcoin/sovereign-university-api
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=sha-

      - name: Set Docker image metadata for web
        uses: docker/metadata-action@v5
        id: meta-web
        with:
          images: ghcr.io/decouvrebitcoin/sovereign-university-web
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=sha-

      - name: Build and push Docker image for api
        uses: docker/bake-action@v4
        with:
          push: true
          files: |
            ./docker-bake.hcl
            ${{ steps.meta-api.outputs.bake-file }}
          targets: api

      - name: Build and push Docker image for web
        uses: docker/bake-action@v4
        with:
          push: true
          files: |
            ./docker-bake.hcl
            ${{ steps.meta-web.outputs.bake-file }}
          targets: web

      - name: Copy Docker files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'docker/compose.yml,docker/cdn'
          overwrite: true
          strip_components: 1
          target: ${{ github.ref == 'refs/heads/main' && 'mainnet' || 'testnet' }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script_stop: true
          script: |
            cd ${{ github.ref == 'refs/heads/main' && 'mainnet' || 'testnet' }}
            docker compose pull
            docker compose stop || true
            docker compose rm -f || true
            docker compose up -d
